export const PreferenceKeys = {
  // UserInfo: 'UserInfo',
  // CurentDevice: 'CurrentDevice',
  // MyDevices: 'MyDevices',
  // ListSources: 'ListSources',
  // LibraryData: 'LibraryDatas',
  // ListChannels: 'ListChannels',
  // RecentData: 'RecentData',
  // VoiceSpeed: 'VoiceSpeed',
  // VoiceId: 'VoiceId',
  // LangTransFrom: 'LangTransFrom',
  // LangTransTo: 'LangTransTo',
  // SortType: 'SortType',
  // ShowAppIntro: 'ShowAppIntro',
  // FirstRun: 'FirstRun',
  // ExpireTimeMS: 'ExpireTimeMS',
  // LastTimeServerMS: 'LastTimeServerMS',
  UserToken: 'UserToken',
}
